### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by yudizhangzyd** [jydu/maffilter#12]
Hi there, 

I was trying to compile maffilter from the source, but I have:

/home/yudiz/local/bpp/dev/sources/jydu-maffilter-c975f4d/MafFilter/MafFilter.cpp: In function ‘int main(int, char**)’:
/home/yudiz/local/bpp/dev/sources/jydu-maffilter-c975f4d/MafFilter/MafFilter.cpp:1219:59: error: ‘class bpp::BppOSubstitutionModelFormat’ has no member named ‘read’
 1219 |           unique_ptr<SubstitutionModel> model(modelReader.read(&AlphabetTools::DNA_ALPHABET, modelDesc, 0, true));
      |                                                           ^~~~
make[2]: *** [MafFilter/CMakeFiles/maffilter.dir/build.make:63: MafFilter/CMakeFiles/maffilter.dir/MafFilter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:197: MafFilter/CMakeFiles/maffilter.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

It looks like the read function does not exist anymore, could you please fix this?

**Comment by jydu** [comment]
This is now fixed (needs a pull from bpp-phyl and maffilter). We are currently preparing the new version of Bio++, so expect some more temporary instabilities. It would be advisable to use the latest stable version of the libs and maffilter.
