### ISSUE TITLE
phylip format filter

### ISSUE THREAD

**Issue by yywyaoyaowu** [jydu/maffilter#17]
Hi
I tried to use mafFilter to filter out the alignment with fewer 3 species. While I don't have the maf format input, I only have the phlip format. Do you have any tools for phylip format filter? Or anytools that can transfer phylip into maf? Thanks very much!
Yao

**Comment by jydu** [comment]
Dear Yao,

MafFilter cannot read a file in phylip format, as this format does not permit to encode synteny breaks for instance.
I am not aware of any converter... I once had to convert a fasta file generated by a simulator (so no synteny break, just SNPs), and I made a script with biopython for that purpose.

Best,

Julien.
