### ISSUE TITLE
error with Subset: Object's name does not exist in container

### ISSUE THREAD

**Issue by lassancejm** [jydu/maffilter#18]
Hi, 

I am trying to use maffilter (MAF Filter, version 1.3.1) to manipulate a maf file produced by ProgressiveCactus. 

I am encountering the following error when I try to output a new file restricted to a few species in the alignment:
```
MappedNamedContainer::removeObject : Object's name does not exist in container : OLDFIELD.scaffold00366
	from  bpp::VectorMappedContainer<bpp::Sequence>::removeObject
	from  bpp::SequenceFilterMafIterator::analyseCurrentBlock_
	from  bpp::AbstractMafIterator::nextBlock
	from  bpp::OutputMafIterator::analyseCurrentBlock_
	from  bpp::AbstractMafIterator::nextBlock
	from  /n/home01/lassance/.local/bin/maffilter(main+0x1f23) [0x45bbb3]
```

here the param file I used:
```
input.file=ProgressiveCactus.aln.maf
input.format=Maf
output.log=maffilter.log
maf.filter=\
	SelectChr(ref_species=DEERMOUSE,chromosome=chr23),\
Subset(species=(MOUSE,DEERMOUSE),strict=yes,keep=no,remove_duplicates=no),\
Output(file=data.filterered.maf,\
compression=none,\
mask=no)
```
Any hint on what is happening here would be welcome.

Thanks,

**Comment by jydu** [comment]
Hi,

May I first ask how you installed MafFilter? Did you use one of the released versions or did you compile it from the master branch from GitHub (using the latest Bio++ version from GitHub too) ?

Julien.

**Comment by lassancejm** [comment]
I actually tried both the latest released version and the Github, and I end up with the same error message. 
Re Bio++, I had some issues compiling some of released versions, so ended up compiling from the respective master branches as well.

**Comment by jydu** [comment]
Hi,

Would it be possible for you to share the input maf file (or part of it), so that I try to solve the issue? (email address can be found here https://www.evolbio.mpg.de/2996566/group_molsysevolution)

Best,

Julien.

**Comment by lassancejm** [comment]
Putting this here, so if someone has the same issue, maybe they could try this fix. 

If using a linux system, a working solution is to use the standalone executable available here: https://github.com/jydu/maffilter/releases.

**Comment by andrewSharo** [comment]
Thanks lassancejm, I ran into this same issue, and the standalone executable (https://github.com/jydu/maffilter/releases/download/v1.3.1/maffilter-x86_64-bin-static-1.3.1-2.tar.gz) solved the problem.

**Comment by jydu** [comment]
I could reproduce the issue. This is due to our current major upgrade of the Bio++ libraries. We're working on it, bear with us :s Meanwhile it is recommended to use the last stable version (executable or using the corresponding tag on the master branch).
