### ISSUE TITLE
error in liftover for inversion

### ISSUE THREAD

**Issue by leejimmy93** [jydu/maffilter#20]
Thanking you for writing this amazing tool for working with MAF, I found this tool really easy to use. Thank you! 
Besides that, I found a small error and wondering whether you can fix it. 
I used liftover function to identify corresponding coordinate in genome B for aligned bases between genome A and B in a MAF file. However, when checking the output using a dotplot, it looks like for all inversions in B relative to A, the corresponding coordinates are incorrect. The generated sp1_to_sp2.tln file has "corresponding begin in genome B for inversion = chrom length - corresponding begin in genome B for inversion in MAF file", although the correct corresponding positions should just be corresponding begin in genome B for inversion in MAF file. And this error propagate through the entire inversion. I am wondering whether this can be fixed in the code and so users don't have to run additional round of computation to correct those errors. 
Thank you! 

Ruijuan

**Comment by jydu** [comment]
Hi,

This looks troublesome... this should only happen if genome B is on the negative strand. Would you happen to have an example file and corresponding script that can reproduce the issue?

Best,

Julien.

**Comment by leejimmy93** [comment]
Hi Julien, 

Thanks for the quick reply! here are the data (https://github.com/leejimmy93/test) and liftover.sh is how I used MafFilter. I downloaded the executable from https://github.com/jydu/maffilter/releases/tag/v1.3.1. 

I am looking forward to your reply! 
Thanks again! 
Ruijuan

**Comment by jydu** [comment]
Dear Ruijuan,

Thanks for the data. Can you point me to one particular gene whose coordinates are wrongly translated?

Thanks,

Julien.

**Comment by leejimmy93** [comment]
Hi Julien, 
Thanks for the quick reply again!!!

The first block that are wrongly translated is the one below in test.maf.gz
a score=-538102    
s B73.10 8283017 5390 + 150982314
s Mo17.10 8389831 25618 - 149041351

these block are translated as below in the test.tln file: 
chr.ref strand.ref      begin.ref       end.ref chr.target      strand.target   begin.target    end.target
10      +       8283407 8285407 10      -       140651121       140628253
10      +       8283407 8285407 10      -       140651121       140628253
10      +       8287040 8289040 10      -       140626620       NA
10      +       8360887 8362887 10      -       140625638       140596629
10      +       8366417 8368417 10      -       140593221       140590132
10      +       8464484 8466484 10      -       NA      NA
10      +       8466885 8468885 10      -       NA      NA
10      +       8541362 8543362 10      -       NA      140489892
10      +       8544872 8546872 10      -       140488084       140472511
10      +       8590207 8592207 10      -       140431140       NA
10      +       8592971 8594971 10      -      

The "begin.target" should be somewhere close to 8389831, which is listed in the test.maf.gz file, however, it seems like 140651121 was calculated by subtracting some value from 149041351, which is the chromosome length. I tested the liftover process on a synthetic gff3 file containing each base pair, and it is clear to me that the start position of each inversion (alignment on negative strand of genome B) is calculated by subtracting the true corresponding coordinate from the chromsome length, and every base aligned to the negative strand would get a wrong liftover coordinate. 

Thank you! 
Ruijuan

**Comment by jydu** [comment]
Dear Ruijuan,

I do not understand why you think it is an error. According to the MAF format description:

> start -- The start of the aligning region in the source sequence. This is a zero-based number. If the strand field is "-" then this is the start relative to the reverse-complemented source sequence 

(see https://genome.ucsc.edu/FAQ/FAQformat.html#format5).

So in the MAF file, the inverted sequences are indexed from the reverse complement. 8389831 is not a coordinate from the original genome, but from the reverse complement.

LiftOver gives the coordinates according to the original genome sequence, that is, the + strand, and therefore the coordinate has to be subtracted from the chr length. Or did I misunderstand your point?

Julien.

**Comment by leejimmy93** [comment]
Dear Julien, 

Thank you so much for the quick reply again! Now it looks like this is actually an error from the MAF file, where the start coordinate for the block should be chromosome length - 8389831 instead of 8389831 since this is an inversion. 
Thank you again! Thank you for writing such a nice tool!
