### ISSUE TITLE
MafSequence::splitNameIntospeciesAndChromosome(). Invalid sequence name: Vibrio_cholerae_strain_N2768

### ISSUE THREAD

**Issue by jhcuarta** [jydu/maffilter#23]
Hi

I encountered this error while running the pipeline

input.file=alignment.maf
output.log=alignment.maffilter.log
input.dots=as_unresolved
maf.filter=OrderFilter(reference=ATCC_25872_EPFL, do_unsorted=discard, do_overlapping=discard), RemoveEmptySequences(unresolved_as_gaps=yes), SequenceStatistics(statistics=(BlockLength, AlnScore, BlockCounts), ref_species=ATCC_25872_EPFL, file=data.statistics.csv, compression=none), DistanceEstimation(method=ml, model=K80(kappa=2), rate=Gamma(n=4, alpha=0.5), parameter_estimation=initial, max_freq_gaps=0.33, gaps_as_unresolved=yes, profiler=std, message_handler=none, extended_names=yes), DistanceBasedPhylogeny(method=bionj, dist_mat=MLDistance)

******************************************************************
*                  MAF Filter, version 1.3.1                     *
* Author: J. Dutheil                        Created on  10/09/10 *
*                                           Last Modif. 18/08/18 *
******************************************************************

Parsing options:
Parsing file parameter for options.
WARNING!!! Parameter input.format not specified. Default used instead: Maf
WARNING!!! Parameter input.file.compression not specified. Default used instead: none
Maf 'dotted' alignment input...........: converted to unresolved
WARNING!!! Parameter input.check_sequence_size not specified. Default used instead: 1
Reading file...........................: alignment.maf as Maf
Output log file........................: alignment.maffilter.log
-------------------------------------------------------------------
Adding filter..........................: OrderFilter
WARNING!!! Parameter verbose not specified. Default used instead: 1
-- Verbose.............................: yes
-- Reference species...................: ATCC_25872_EPFL
-- Unsorted block action...............: discard
-- Overlapping block action............: discard
-------------------------------------------------------------------
Adding filter..........................: RemoveEmptySequences
WARNING!!! Parameter verbose not specified. Default used instead: 1
-- Verbose.............................: yes
-- Unresolved as gaps..................: yes
-------------------------------------------------------------------
Adding filter..........................: SequenceStatistics
WARNING!!! Parameter verbose not specified. Default used instead: 1
-- Verbose.............................: yes
-- Adding statistic....................: Number of sites. <BlockLength>
-- Adding statistic....................: Alignment score. <AlnScore>
WARNING!!! Parameter suffix not specified. Default used instead: 
-- Adding statistic....................: Character counts (). <Counts>
-- Output file.........................: data.statistics.csv
-- File compression....................: none
-- Reference species...................: ATCC_25872_EPFL
-------------------------------------------------------------------
Adding filter..........................: DistanceEstimation
WARNING!!! Parameter verbose not specified. Default used instead: 1
-- Verbose.............................: yes
-- Method..............................: ml
-- Max. frequency of gaps..............: 0.33
-- Gaps as unresolved..................: yes
-- Use extended names in matrix........: yes
Substitution model.....................: K80
External frequencies initialization for: None
Parameter found........................: K80.kappa=2
Distribution...........................: Gamma
Number of classes......................: 4
Parameter found........................: Gamma.alpha=0.5
- Category 0 (Pr = 0.25) rate..........: 0.0333878
- Category 1 (Pr = 0.25) rate..........: 0.251916
- Category 2 (Pr = 0.25) rate..........: 0.820268
- Category 3 (Pr = 0.25) rate..........: 2.89443
-- Optimization profile in.............: std
-- Optimization messages in............: none
-- Block-wise matrices are registered a: MLDistance
-------------------------------------------------------------------
Adding filter..........................: DistanceBasedPhylogeny
WARNING!!! Parameter verbose not specified. Default used instead: 1
-- Verbose.............................: yes
-- Reading distance matrix from........: MLDistance
-- Build distance tree using...........: bionj
-- Writing block-wise trees to.........: BioNJ
Parsing...
MafSequence::splitNameIntospeciesAndChromosome(). Invalid sequence name: Vibrio_cholerae_strain_N2768

Should I rename all the genomes files before creating the .maf file
Any help

**Comment by jhcuarta** [comment]
Hi
I renamed all the genomes and still getting the same error

MafSequence::splitNameIntospeciesAndChromosome(). Invalid sequence name: strain_N2768

here's the link with the new alignment

https://drive.google.com/file/d/1_3Fahf7YBTFiZbiiwpm7h76MC9Df1Z7f/view?usp=sharing

**Comment by jydu** [comment]
Hi,

It seems that your file does not strictly follow the maf format: sequence names should be of the form species.contig. There should at least be one dot in the sequence names. If the species has only one chromosome, it should be renamed as sthg like strain.chr1 for instance.

hope this helps,

Julien.
