### ISSUE TITLE
SelectOrphans remove_duplicates=yes not work!!

### ISSUE THREAD

**Issue by song984888** [jydu/maffilter#29]
# MAF Filter, version 1.3.1

# param file: 
DATA=my.hal_ref_JNI
input.file=$(DATA).maf.gz
input.file.compression=gzip
input.format=Maf
minLength=5
output.log=maffilter.noDup.min5.log
maf.filter=                                                                \
    SelectOrphans(                                                                \
        species=(Alfaropsis_roxburghiana,Carya_cathayensis,Carya_illinoinensis,Carya_sinensis,Cyclocarya_paliurus,Engelhardia_specata,Juglans_californica,Juglans_mandshurica,Juglans_nigra,Platycarya_longipes,Platycarya_strobilacea,Pterocarya_stenoptera,Rhoiptelea_chiliantha), \
        strict=yes, \
        remove_duplicates=yes),                                             \
    Output(                                 \
        file=$(DATA)_filtered.maf,          \
        compression=none,                   \
        mask=yes),                          \

#Output sample:  # Engelhardia_specata duplication still exists!!!!
##maf version=1 program=Bio++
#
a
s Juglans_nigra.pseudoChr01                 18196 15 +  40579570 CTGGAGTTTGTG------------CGT
s Alfaropsis_roxburghiana.AroxChr01       2351182 13 -  74945250 CCGGAGTTTG--------------CGT
s Carya_cathayensis.Chr03                55701963 14 -  55786669 CTG-AGTTTGTG------------CGT
s Carya_illinoinensis.CM031811.1        113048486 15 - 113217320 CTGGAGTTTGCG------------CGT
s Carya_sinensis.Chr03                   48301686 15 -  48359112 CTGGAGTTTGTG------------CGT
s Cyclocarya_paliurus.DCPChr01              17943 15 +  45280996 CTGGAGTTTGTG------------CGT
s Engelhardia_specata.Chr01                 26368 13 -  61758315 CCGGAGTCTG--------------CGT
s Engelhardia_specata.Chr16              30659996 13 -  30872587 CCGAAGTCTG--------------CGT
s Juglans_californica.JAKSXK010000002.1     27226 15 -  43958334 CTGGAGTTTGTG------------CGT
s Juglans_mandshurica.chr3                  13572 15 +  44088235 CTGGAGTTTGTG------------CGT
s Platycarya_longipes.PlonChr06          32580777 11 -  33104143 ----AGTTGGTG------------TTT
s Platycarya_longipes.PlonChr09             67595 11 -  53562260 ----AGTTGGTG------------TTT
s Platycarya_strobilacea.PstrChr03         116976 11 -  55728008 ----AGTTGGTG------------TTT
s Platycarya_strobilacea.PstrChr08       32144999 11 -  35605095 ----AGTTGGTG------------TTT
s Pterocarya_stenoptera.CTG_7               18802 22 +   8137472 -----GTTCTTGTCAAGTACATTACAT
s Rhoiptelea_chiliantha.Chr2               266947 15 -  31162655 TTGGGGTATGGA------------TGT

**Comment by jydu** [comment]
Indeed, I look into it as soon as possible...

**Comment by jydu** [comment]
Hi, this is now fixed. The remove_duplicates option was indeed wrongly parsed. The error was corrected upstream, you will need an up-to-date bio++ libraries to compile the latest maffilter. If needed, I can send a standalone version for Linux 64 bits.

Thanks for reporting!

Julien.

**Comment by song984888** [comment]
Thanks for your reply.
please send it me to songhongtao@bnu.edu.cn  



> Hi, this is now fixed. The remove_duplicates option was indeed wrongly parsed. The error was corrected upstream, you will need an up-to-date bio++ libraries to compile the latest maffilter. If needed, I can send a standalone version for Linux 64 bits.
> 
> Thanks for reporting!
> 
> Julien.
