### ISSUE TITLE
MafFilter possibly requiring incorrect version of bpp-phyl-omics (v3.0.0 instead of v2.4.0)?

### ISSUE THREAD

**Issue by jasonsydes** [jydu/maffilter#3]
Hello there!

Thank you for MafFilter!  

I was able to compile and install from source version 1.2.1 of MafFilter.  To do so, that also required that I build many of the bpp-* librariers (all version 2.3.2).

However, I'm now trying to build your new version 1.3.0 of MafFilter, and it seems to be requiring version 3.0.0 of the bpp-* libraries.  The specific error I'm receiving is:
```
CMake Error at CMakeLists.txt:66 (find_package):
  Could not find a configuration file for package "bpp-phyl-omics" that is
  compatible with requested version "3.0.0".

  The following configuration files were considered but not accepted:

    /path/to/bpp-phyl-omics/2.3.2/lib64/cmake/bpp-phyl-omics/bpp-phyl-omics-config.cmake, version: 2.0.0



-- Configuring incomplete, errors occurred!
```
Unfortunately, from what I can tell, there is no public version 3.0.0 of bpp-phyl-omics.  The most recent version appears to be 2.4.0 for all of the bpp-* libraries.  Are you perhaps building your copy of MafFilter against a private copy of the  Bio++ libraries?

Thank you!
Jason Sydes

**Comment by jydu** [comment]
Hi Jason,

I know it is a bit confusing, but there are two types of version numbers: one is the package version number, with current version 2.4.0 for Bio++. While this has not always been the case, currently all Bio++ libraries share the same version number for commodity. The other number is the library interface number, following the libtool scheme. To make it short, when changes are introduced that breaks the library interface, we have to increase this number. So minor revisions can lead to interface number change while some others do not, meaning that there is no direct correspondance between these numbers and the package version number. To give you an idea, here are the interface numbers for Bio++ version 2.4.0:
bpp-core: 4
bpp-seq: 12
bpp-phyl: 12
bpp-popgen: 8
bpp-seq-omics: 3
bpp-phyl-omics: 3

Finally, the cmake version follows the library interface numbering. So version 3.0.0 of bpp-phyl-omics corresponds to version 2.4.0 of Bio++, and installing this one should allows you to compile MafFilter without error. Note that in case several versions of the libs are present, maffilter might still attempt to link against the wrong one. This can usually be solved by setting the CMAKE_INSTALL_PREFIX option in the cmake command.

Hope this helps,

Julien.

**Comment by jasonsydes** [comment]
Ah, thank you Julien!  Ok, I went ahead and upgraded to 2.4.0 for those 7 bpp-* dependencies, and I've now successfully built MafFilter.

Thank you for your assistance!
Jason
