### ISSUE TITLE
Parsing error with output from Cactus

### ISSUE THREAD

**Issue by jydu** [jydu/maffilter#32]
Cactus outputs maf files with two line breaks after the specified block size. MafFilter with then consider that the file is finished and will not ready any further data!

Fix: allow multiple empty lines between blocks.

**Comment by jydu** [comment]
Fixed remotely in bpp-seq-omicds.

**Comment by sosie101** [comment]
I wanted to note that I installed maffilter v1.3.1 from the .tar.gz file using this link: https://github.com/jydu/maffilter/releases. I found that when I run SequenceStatistics on my .maf file from Cactus, I only get results from the first chromosome in the .maf file. I removed all instances of consecutive empty lines with just one and it fixed the problem.

**Comment by jydu** [comment]
Yes, the bug was fixed after version 1.3.1. The fix will be included in the next release; meanwhile, one has to compile maffilter from the repository source code to get the fix. (A new release is expected in the coming months.)
