### ISSUE TITLE
Build on Ubuntu Xenial

### ISSUE THREAD

**Issue by hinz1** [jydu/maffilter#7]
cmake gives me the following error: 

```
CMake Error at CMakeLists.txt:67 (find_package):
  By not providing "Findbpp-phyl-omics.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "bpp-phyl-omics", but CMake did not find one.

  Could not find a package configuration file provided by "bpp-phyl-omics"
  (requested version 3.0.0) with any of the following names:

    bpp-phyl-omicsConfig.cmake
    bpp-phyl-omics-config.cmake

  Add the installation prefix of "bpp-phyl-omics" to CMAKE_PREFIX_PATH or set
  "bpp-phyl-omics_DIR" to a directory containing one of the above files.  If
  "bpp-phyl-omics" provides a separate development package or SDK, be sure it
  has been installed.
```

libbpp-*-dev packages are installed via repos, Xenial has them in version 2.1.0 
(If I understand correctly the CMakeList asks for versions 3.0.0 and 8.0.0. The newest verion of bpp is 2.4 on GitHub...?) 
Is there a possibility to build maffilter on my system?

**Comment by jydu** [comment]
Hi,

A maffilter package should be available for Xenial. If you want to get the latest maffilter version, you will need to install the latest Bio++ libraries from github too (compilation from sources).

Hope this helps,

Julien.

**Comment by hinz1** [comment]
Thank you for your reply. I'd love to just use a packaged version but I can't find maffilter in the official Xenial-repos. Do I have to search with a different name or do I have to add a PPA...?

**Comment by jydu** [comment]
Indeed, Xenial is a bit old, packages are for later versions... did you try the binary version (1.3.0) available from github? This is a standalone executable that should work on xenial...
